extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern Lights1 jrb_dl_Material_lights;
extern Vtx jrb_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx jrb_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_Material[];
extern Gfx jrb_dl_Cube_mesh_layer_1[];
